package com.adventnet.nms.example.southboundcorba.device;


/**
* com/adventnet/nms/example/southboundcorba/device/_CORBAAgentStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from /advent/nmsbuild/WebNMS2.3/examples/corbasouthbound/idls/Device.idl
* Tuesday, August 7, 2001 8:15:00 PM GMT+05:30
*/

public class _CORBAAgentStub extends org.omg.CORBA.portable.ObjectImpl implements com.adventnet.nms.example.southboundcorba.device.CORBAAgent
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _CORBAAgentStub ()
  {
    super ();
  }

  public _CORBAAgentStub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public String CORBAget (String corbaIdentifier)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("CORBAget", true);
       _out.write_string (corbaIdentifier);
       _in = _invoke (_out);
       String __result = _in.read_string ();
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return CORBAget (corbaIdentifier);
    } finally {
        _releaseReply (_in);
    }
  } // CORBAget

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/adventnet/nms/example/southboundcorba/device/CORBAAgent:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _CORBAAgentStub
