package com.adventnet.nms.example.southboundcorba.device;


/**
* com/adventnet/nms/example/southboundcorba/device/CORBAAgentHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from /advent/nmsbuild/WebNMS2.3/examples/corbasouthbound/idls/Device.idl
* Tuesday, August 7, 2001 8:15:00 PM GMT+05:30
*/

abstract public class CORBAAgentHelper
{
  private static String  _id = "IDL:com/adventnet/nms/example/southboundcorba/device/CORBAAgent:1.0";

  public static void insert (org.omg.CORBA.Any a, com.adventnet.nms.example.southboundcorba.device.CORBAAgent that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.adventnet.nms.example.southboundcorba.device.CORBAAgent extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.adventnet.nms.example.southboundcorba.device.CORBAAgentHelper.id (), "CORBAAgent");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.adventnet.nms.example.southboundcorba.device.CORBAAgent read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CORBAAgentStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.adventnet.nms.example.southboundcorba.device.CORBAAgent value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.adventnet.nms.example.southboundcorba.device.CORBAAgent narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.adventnet.nms.example.southboundcorba.device.CORBAAgent)
      return (com.adventnet.nms.example.southboundcorba.device.CORBAAgent)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new com.adventnet.nms.example.southboundcorba.device._CORBAAgentStub (delegate);
    }
  }

}
