package com.adventnet.nms.example.southboundcorba.device;

/**
* com/adventnet/nms/example/southboundcorba/device/CORBAAgentHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from /advent/nmsbuild/WebNMS2.3/examples/corbasouthbound/idls/Device.idl
* Tuesday, August 7, 2001 8:15:00 PM GMT+05:30
*/

public final class CORBAAgentHolder implements org.omg.CORBA.portable.Streamable
{
  public com.adventnet.nms.example.southboundcorba.device.CORBAAgent value = null;

  public CORBAAgentHolder ()
  {
  }

  public CORBAAgentHolder (com.adventnet.nms.example.southboundcorba.device.CORBAAgent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.adventnet.nms.example.southboundcorba.device.CORBAAgentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.adventnet.nms.example.southboundcorba.device.CORBAAgentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.adventnet.nms.example.southboundcorba.device.CORBAAgentHelper.type ();
  }

}
