package com.adventnet.nms.example.southboundcorba.device;


/**
* com/adventnet/nms/example/southboundcorba/device/CORBAAgent.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from /advent/nmsbuild/WebNMS2.3/examples/corbasouthbound/idls/Device.idl
* Tuesday, August 7, 2001 8:15:00 PM GMT+05:30
*/

public interface CORBAAgent extends CORBAAgentOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAAgent
