file=sorted_results.txt
export file
grep -re "AckFwdSystemLink" $file
grep -re "BackupServerLink" $file
grep -re "BillingServerLink" $file
grep -re "BlackBoxDataConfig" $file
grep -re "BlackBoxLogStream" $file
grep -re "BmgwClientThrottleLink" $file
grep -re "BmgwServerThrottleLink" $file
grep -re "BmgwServerUnavailableLink" $file
grep -re "CORBANode" $file
grep -re "CapacityLicenseLink" $file
grep -re "ClassOfService" $file
grep -re "CnpACL" $file
grep -re "CnpAirFilter" $file
grep -re "CnpCage" $file
grep -re "CnpCageInfo" $file
grep -re "CnpClusterManager" $file
grep -re "CnpClusterManagerPG" $file
grep -re "CnpEmsSensor" $file
grep -re "CnpEmsServer" $file
grep -re "CnpEmsServerPG" $file
grep -re "CnpEthernetPort" $file
grep -re "CnpEthernetPortGroup" $file
grep -re "CnpExtSwitch" $file
grep -re "CnpExternalServer" $file
grep -re "CnpFan" $file
grep -re "CnpFileSystemInfo" $file
grep -re "CnpFruInfo" $file
grep -re "CnpLocationInfo" $file
grep -re "CnpMonDevInfo" $file
grep -re "CnpPEM" $file
grep -re "CnpPSBlackBoxDC" $file
grep -re "CnpPSBlackBoxLS" $file
grep -re "CnpPSCoreFileMgmtLS" $file
grep -re "CnpPayloadServer" $file
grep -re "CnpPayloadServerPG" $file
grep -re "CnpRTM" $file
grep -re "CnpRaid" $file
grep -re "CnpRaidController" $file
grep -re "CnpRaidFan" $file
grep -re "CnpRaidLogicalDrive" $file
grep -re "CnpRaidLogicalUnit" $file
grep -re "CnpRaidPEM" $file
grep -re "CnpRaidPhysicalDrive" $file
grep -re "CnpRaidPort" $file
grep -re "CnpRaidPortGroup" $file
grep -re "CnpServerInfo" $file
grep -re "CnpShelfEEPROM" $file
grep -re "CnpShmm" $file
grep -re "CnpShmmBMC" $file
grep -re "CnpSwitch" $file
grep -re "CnpSwitchUnit" $file
grep -re "CnpSystemAlarmPanel" $file
grep -re "CnpSystemInfo" $file
grep -re "CnpTermServer" $file
grep -re "Congestion" $file
grep -re "ConnectivityData" $file
grep -re "Constituent" $file
grep -re "ContentAdaptationLink" $file
grep -re "CoreFileMgmtLogStream" $file
grep -re "DataObject" $file
grep -re "DiskUsage" $file
grep -re "DnsServerLink" $file
grep -re "Endpoint" $file
grep -re "EnumServerLink" $file
grep -re "EnumServiceLink" $file
grep -re "EsmeLink" $file
grep -re "EsmeLocalConnectionLink" $file
grep -re "EsmeNetworkConnectionLink" $file
grep -re "EsmeQueuedMessageLink" $file
grep -re "EventControl" $file
grep -re "ExternalIPLink" $file
grep -re "FileSystem" $file
grep -re "GeoRedSMSReplLink" $file
grep -re "GeoRedSMSReplThrottleLink" $file
grep -re "HapNeControl" $file
grep -re "HssServerLink" $file
grep -re "HssServerThrottleLink" $file
grep -re "HssServerUnavailableConnection" $file
grep -re "ImsGsmGwClientThrottleLink" $file
grep -re "ImsGsmGwServerLink" $file
grep -re "ImsGsmGwServerThrottleLink" $file
grep -re "InterMateLink" $file
grep -re "Interface" $file
grep -re "InterfaceContainer" $file
grep -re "IpAddress" $file
grep -re "IpConfig" $file
grep -re "LnpServerLink" $file
grep -re "LoadBalancerLink" $file
grep -re "LogStream" $file
grep -re "LogStreamDataConfig" $file
grep -re "LogicalContainer" $file
grep -re "LogicalElement" $file
grep -re "LogicalUnit" $file
grep -re "LogicalUnitStream" $file
grep -re "M2paLink" $file
grep -re "M2paLogicalUnit" $file
grep -re "M2paSystemInfo" $file
grep -re "ManagedGroupObject" $file
grep -re "ManagedObject" $file
grep -re "MateLink" $file
grep -re "MessagingSystem" $file
grep -re "Mm1Link" $file
grep -re "MpSystemConfig" $file
grep -re "MsgArchiveServerLink" $file
grep -re "MsgBladeLU" $file
grep -re "MsgBladeLUContainer" $file
grep -re "MsmMemUtilization" $file
grep -re "Network" $file
grep -re "NetworkElementManagement" $file
grep -re "Node" $file
grep -re "PeerMMSCLink" $file
grep -re "PersonalizationConfig" $file
grep -re "PhysicalContainer" $file
grep -re "PhysicalElement" $file
grep -re "PhysicalEntity" $file
grep -re "PhysicalSubUnit" $file
grep -re "PhysicalUnit" $file
grep -re "PhysicalUnitStream" $file
grep -re "PortObject" $file
grep -re "PrepaidServerLink" $file
grep -re "PrepaidServerThrottleLink" $file
grep -re "Printer" $file
grep -re "ProtectionGroup" $file
grep -re "QueueOverflow" $file
grep -re "RelationObject" $file
grep -re "RemoteSMSCThrottleLink" $file
grep -re "SBNE" $file
grep -re "SCSCFClientThrottleLink" $file
grep -re "SCSCFServerThrottleLink" $file
grep -re "SmppClientLink" $file
grep -re "SmppServerLink" $file
grep -re "SmscLink" $file
grep -re "SmscLocalConnectionLink" $file
grep -re "SmscNetworkConnectionLink" $file
grep -re "SmscQueuedMessageLink" $file
grep -re "SmtpClientLink" $file
grep -re "SmtpLink" $file
grep -re "SmtpLocalConnectionLink" $file
grep -re "SmtpNetworkConnectionLink" $file
grep -re "SmtpQueuedMessageLink" $file
grep -re "SmtpServerLink" $file
grep -re "SnmpInterface" $file
grep -re "SnmpNode" $file
grep -re "SpamServerLink" $file
grep -re "SpamServerThrottleLink" $file
grep -re "SpamServerUnavailableConnection" $file
grep -re "Ss7AssociationLink" $file
grep -re "Ss7PCLink" $file
grep -re "Ss7Service" $file
grep -re "StatSizeAuditLink" $file
grep -re "StatisticsThreshold" $file
grep -re "SubLdapServerLink" $file
grep -re "SwitchObject" $file
grep -re "TL1Interface" $file
grep -re "TL1Node" $file
grep -re "TL1Node" $file
grep -re "TL1Node" $file
grep -re "TapClientLink" $file
grep -re "TapLink" $file
grep -re "TapLocalConnectionLink" $file
grep -re "TapNetworkConnectionLink" $file
grep -re "TopoObject" $file
grep -re "TranscoderLink" $file
grep -re "UsageControlServiceLink" $file
grep -re "VaspLink" $file
grep -re "XmlClientLink" $file
grep -re "XmlcLocalConnectionLink" $file
grep -re "XmlcNetworkConnectionLink" $file
