file=ics_script_for_reverse_migration_Dec_20.sql
export file
##checking migration of topodb tables 
grep -wre "PhysicalEntity" $file | wc -l
grep -wre "PhysicalContainer" $file | wc -l
grep -wre "PhysicalElement" $file | wc -l
grep -wre "PhysicalSubUnit" $file | wc -l
grep -wre "PhysicalUnit" $file | wc -l
grep -wre "LogicalContainer" $file | wc -l
grep -wre "LogicalElement" $file | wc -l
grep -wre "LogicalUnit" $file | wc -l
grep -wre "ProtectionGroup" $file | wc -l
grep -wre "SBNE" $file | wc -l
grep -wre "NetworkElementManagement" $file | wc -l
grep -wre "DataObject" $file | wc -l
grep -wre "IpConfig" $file | wc -l
grep -wre "EventControl" $file | wc -l
grep -wre "RelationObject" $file | wc -l
grep -wre "PhysicalUnitStream" $file | wc -l
grep -wre "LogicalUnitStream" $file | wc -l
grep -wre "LogStreamDataConfig" $file | wc -l
grep -wre "LogStream" $file | wc -l
grep -wre "Constituent" $file | wc -l
grep -wre "ConnectivityData" $file | wc -l
grep -wre "Interface" $file | wc -l
grep -wre "InterfaceContainer" $file | wc -l
grep -wre "Endpoint" $file | wc -l
grep -wre "BlackBoxLogStream" $file | wc -l
grep -wre "CoreFileMgmtLogStream" $file | wc -l
grep -wre "HapNeControl" $file | wc -l
grep -wre "CnpEthernetPortGroup" $file | wc -l
grep -wre "CnpFileSystemInfo" $file | wc -l
grep -wre "CnpRaidPortGroup" $file | wc -l
grep -wre "CnpServerInfo" $file | wc -l
grep -wre "CnpEthernetPort" $file | wc -l
grep -wre "CnpRaidPort" $file | wc -l
grep -wre "CnpCageInfo" $file | wc -l
grep -wre "CnpACL" $file | wc -l
grep -wre "CnpFruInfo" $file | wc -l
grep -wre "CnpSystemInfo" $file | wc -l
grep -wre "CnpLocationInfo" $file | wc -l
grep -wre "CnpMonDevInfo" $file | wc -l
grep -wre "CnpCage" $file | wc -l
grep -wre "CnpClusterManager" $file | wc -l
grep -wre "CnpClusterManagerPG" $file | wc -l
grep -wre "CnpEmsServer" $file | wc -l
grep -wre "CnpEmsServerPG" $file | wc -l
grep -wre "CnpExtSwitch" $file | wc -l
grep -wre "CnpFan" $file | wc -l
grep -wre "CnpPEM" $file | wc -l
grep -wre "CnpRaid" $file | wc -l
grep -wre "CnpRaidController" $file | wc -l
grep -wre "CnpRaidFan" $file | wc -l
grep -wre "CnpRaidLogicalDrive" $file | wc -l
grep -wre "CnpRaidLogicalUnit" $file | wc -l
grep -wre "CnpRaidPEM" $file | wc -l
grep -wre "CnpRaidPhysicalDrive" $file | wc -l
grep -wre "CnpShmm" $file | wc -l
grep -wre "CnpSwitch" $file | wc -l
grep -wre "CnpTermServer" $file | wc -l
grep -wre "CnpSwitchUnit" $file | wc -l
grep -wre "CnpRTM" $file | wc -l
grep -wre "BlackBoxDataConfig" $file | wc -l
grep -wre "CnpAirFilter" $file | wc -l
grep -wre "CnpSystemAlarmPanel" $file | wc -l
grep -wre "CnpShelfEEPROM" $file | wc -l
grep -wre "CnpShmmBMC" $file | wc -l
grep -wre "CnpEmsSensor" $file | wc -l
grep -wre "CnpExternalServer" $file | wc -l
grep -wre "EnumServerLink" $file | wc -l
grep -wre "SubLdapServerLink" $file | wc -l
grep -wre "PeerMMSCLink" $file | wc -l
grep -wre "SmppServerLink" $file | wc -l
grep -wre "SmtpServerLink" $file | wc -l
grep -wre "TranscoderLink" $file | wc -l
grep -wre "VaspLink" $file | wc -l
grep -wre "Mm1Link" $file | wc -l
grep -wre "BackupServerLink" $file | wc -l
grep -wre "PrepaidServerLink" $file | wc -l
grep -wre "TapLink" $file | wc -l
grep -wre "MateLink" $file | wc -l
grep -wre "Ss7PCLink" $file | wc -l
grep -wre "SmtpClientLink" $file | wc -l
grep -wre "SmppClientLink" $file | wc -l
grep -wre "Ss7AssociationLink" $file | wc -l
grep -wre "BillingServerLink" $file | wc -l
grep -wre "MsgArchiveServerLink" $file | wc -l
grep -wre "DnsServerLink" $file | wc -l
grep -wre "AckFwdSystemLink" $file | wc -l
grep -wre "ExternalIPLink" $file | wc -l
grep -wre "EsmeLink" $file | wc -l
grep -wre "SmscLink" $file | wc -l
grep -wre "TapClientLink" $file | wc -l
grep -wre "XmlClientLink" $file | wc -l
grep -wre "InterMateLink" $file | wc -l
grep -wre "EsmeNetworkConnectionLink" $file | wc -l
grep -wre "EsmeQueuedMessageLink" $file | wc -l
grep -wre "LnpServerLink" $file | wc -l
grep -wre "EsmeLocalConnectionLink" $file | wc -l
grep -wre "SmscLocalConnectionLink" $file | wc -l
grep -wre "SmscNetworkConnectionLink" $file | wc -l
grep -wre "SmscQueuedMessageLink" $file | wc -l
grep -wre "TapLocalConnectionLink" $file | wc -l
grep -wre "TapNetworkConnectionLink" $file | wc -l
grep -wre "XmlcLocalConnectionLink" $file | wc -l
grep -wre "XmlcNetworkConnectionLink" $file | wc -l
grep -wre "LoadBalancerLink" $file | wc -l
grep -wre "BmgwServerThrottleLink" $file | wc -l
grep -wre "BmgwServerUnavailableLink" $file | wc -l
grep -wre "UsageControlServiceLink" $file | wc -l
grep -wre "DiskUsage" $file | wc -l
grep -wre "FileSystem" $file | wc -l
grep -wre "HssServerLink" $file | wc -l
grep -wre "HssServerUnavailableConnection" $file | wc -l
grep -wre "ImsGsmGwServerLink" $file | wc -l
grep -wre "ImsGsmGwServerThrottleLink" $file | wc -l
grep -wre "SCSCFServerThrottleLink" $file | wc -l
grep -wre "HssServerThrottleLink" $file | wc -l
grep -wre "ContentAdaptationLink" $file | wc -l
grep -wre "SmtpLink" $file | wc -l
grep -wre "SmtpLocalConnectionLink" $file | wc -l
grep -wre "SmtpNetworkConnectionLink" $file | wc -l
grep -wre "SmtpQueuedMessageLink" $file | wc -l
grep -wre "StatSizeAuditLink" $file | wc -l
grep -wre "CapacityLicenseLink" $file | wc -l
grep -wre "PersonalizationConfig" $file | wc -l
grep -wre "SpamServerLink" $file | wc -l
grep -wre "SpamServerThrottleLink" $file | wc -l
grep -wre "SpamServerUnavailableConnection" $file | wc -l
grep -wre "PrepaidServerThrottleLink" $file | wc -l
grep -wre "M2paLink" $file | wc -l
grep -wre "M2paLogicalUnit" $file | wc -l
grep -wre "M2paSystemInfo" $file | wc -l
grep -wre "GeoRedSMSReplLink" $file | wc -l
grep -wre "GeoRedSMSReplThrottleLink" $file | wc -l
grep -wre "RemoteSMSCThrottleLink" $file | wc -l
grep -wre "MsmMemUtilization" $file | wc -l
grep -wre "MsgBladeLU" $file | wc -l
grep -wre "MsgBladeLUContainer" $file | wc -l
grep -wre "ClassOfService" $file | wc -l
grep -wre "EnumServiceLink" $file | wc -l
grep -wre "Ss7Service" $file | wc -l
grep -wre "Congestion" $file | wc -l
grep -wre "MessagingSystem" $file | wc -l
grep -wre "StatisticsThreshold" $file | wc -l
grep -wre "QueueOverflow" $file | wc -l
grep -wre "BmgwClientThrottleLink" $file | wc -l
grep -wre "ImsGsmGwClientThrottleLink" $file | wc -l
grep -wre "SCSCFClientThrottleLink" $file | wc -l
grep -wre "MpSystemConfig" $file | wc -l
grep -wre "CnpPSBlackBoxLS" $file | wc -l
grep -wre "CnpPSCoreFileMgmtLS" $file | wc -l
grep -wre "CnpPayloadServer" $file | wc -l
grep -wre "CnpPayloadServerPG" $file | wc -l
grep -wre "CnpPSBlackBoxDC" $file | wc -l
grep -wre "ManagedGroupObject " $file | wc -l
grep -wre "TopoObject" $file | wc -l
grep -wre "Node" $file | wc -l
grep -wre "Network" $file | wc -l
grep -wre "SnmpNode" $file | wc -l
grep -wre "SnmpInterface" $file | wc -l
grep -wre "TL1Node" $file | wc -l
grep -wre "TL1Interface" $file | wc -l
grep -wre "IpAddress" $file | wc -l
grep -wre "SwitchObject" $file | wc -l
grep -wre "PortObject" $file | wc -l
grep -wre "Printer" $file | wc -l
grep -wre "CORBANode" $file | wc -l
grep -wre "TL1Node" $file | wc -l
