/*
$Id: SendEmailActionDialog.java,v 1.1.1.1 2006/11/16 15:39:58 gramkumar Exp $
*/
package com.adventnet.nms.eventui;


import java.util.*;
import com.adventnet.nms.eventui.*;
import com.adventnet.nms.eventdb.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.*;
import com.adventnet.nms.util.*;
import java.io.*;

import com.adventnet.snmp.ui.SasFileDialog;

public class SendEmailActionDialog extends javax.swing.JDialog implements ActionListener {
    
    AddAction addAction = null;
    Properties cprop = null;
    JFileChooser chooser = null;
    SasFileDialog attachDialog = null;
    JFrame jf = new JFrame();
    
    public SendEmailActionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        initComponents();
        Icon icon = AddAction.getIcon("images/click.png");//No i18n
        
        jButton2.setIcon(icon);
        jButton3.setIcon(icon);
     	try
        {
            if(!NmsFilterFrame.standAlone)
       	    {
                attachDialog = new SasFileDialog(NmsClientUtil.applet);
		attachDialog.addActionListener(this);
	    }
            else
            {
		chooser =  new JFileChooser(com.adventnet.nms.util.PureUtils.rootDir);
		chooser.addActionListener(this);
	    }
        }
	catch (Exception ex)
	    {
		ex.printStackTrace();
	    }
        
    }
    
    public SendEmailActionDialog(java.awt.Frame parent, boolean modal, AddAction act) {
        this(parent, modal);
        addAction = act;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        smallPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        subject = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        name = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        server = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        file = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        helpButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        smallPanel.setLayout(new java.awt.GridBagLayout());

        smallPanel.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jButton4.setText("x");//No i18n
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        //jButton4.setIconTextGap(0);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel14.add(jButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        jPanel14.add(jSeparator3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 1, 10, 17);
        smallPanel.add(jPanel14, gridBagConstraints);

        jLabel9.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel9.setText("Insert Property");//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 5);
        smallPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel10.setText("Property Name");//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(25, 15, 20, 5);
        smallPanel.add(jLabel10, gridBagConstraints);

        jComboBox1.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 20, 15);
        smallPanel.add(jComboBox1, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(AddAction.sendEmailAction);//No i18n
        setResizable(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(NmsClientUtil.GetString("javaui.filter.NotificationName"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel2.setText(NmsClientUtil.GetString("javaui.filter.EmailAction"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jSeparator1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jPanel3, gridBagConstraints);

        jLabel3.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel3.setText(NmsClientUtil.GetString("javaui.filter.SMTPServer"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(NmsClientUtil.GetString("javaui.filter.ToEmailID"));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(NmsClientUtil.GetString("javaui.filter.FromEmailID"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText(NmsClientUtil.GetString("javaui.filter.Subject"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(NmsClientUtil.GetString("javaui.filter.Message"));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        jButton1.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jButton1.setText(NmsClientUtil.GetString("javaui.filter.Authentication"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 10);
        jPanel2.add(jButton1, gridBagConstraints);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jButton2.setIcon(AddAction.getIcon("images/click.png"));//No i18n
        jButton2.setToolTipText("Append property");//No i18n
        jButton2.setBorderPainted(false);
        //jButton2.setIconTextGap(0);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel12.setLayout(new java.awt.BorderLayout());

        subject.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jPanel12.add(subject, java.awt.BorderLayout.NORTH);

        jPanel4.add(jPanel12, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jButton3.setIcon(AddAction.getIcon("images/click.png"));//No i18n
        jButton3.setToolTipText("Append property");//No i18n
        jButton3.setBorderPainted(false);
        //jButton3.setIconTextGap(0);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel6.add(jButton3, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        msg.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        msg.setLineWrap(true);
        msg.setRows(5);
        msg.setWrapStyleWord(true);
        jScrollPane1.setViewportView(msg);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(jPanel5, gridBagConstraints);

        name.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(name, gridBagConstraints);

        to.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(to, gridBagConstraints);

        from.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(from, gridBagConstraints);

        server.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(server, gridBagConstraints);

        jLabel8.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jLabel8.setText(NmsClientUtil.GetString("javaui.filter.FileAttachment"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel2.add(jLabel8, gridBagConstraints);

        jPanel11.setLayout(new java.awt.BorderLayout());

        file.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jPanel11.add(file, java.awt.BorderLayout.CENTER);

        jButton7.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        jButton7.setText("...");//No i18n
        jButton7.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel11.add(jButton7, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel2.add(jPanel11, gridBagConstraints);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        helpButton.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        helpButton.setText(NmsClientUtil.GetString("javaui.filter.Help"));
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        jPanel10.add(helpButton);

        jPanel8.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel13.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        okButton.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        okButton.setText(NmsClientUtil.GetString("javaui.filter.OK"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel13.add(okButton);

        cancelButton.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
        cancelButton.setText(NmsClientUtil.GetString("javaui.filter.Cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel13.add(cancelButton);

        jPanel8.add(jPanel13, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel2.add(jSeparator2, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton3ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        JPopupMenu jp = new JPopupMenu();

        Vector vec = new Vector();
        vec.addElement("category");//No i18n
        vec.addElement("entity");//No i18n
        vec.addElement("text");//No i18n
        vec.addElement("severity");//No i18n
        vec.addElement("source");//No i18n
        vec.addElement("groupName");//No i18n
        
        for(Enumeration en = vec.elements(); en.hasMoreElements();)
        {
            String str = (String)en.nextElement();
            JMenuItem mi = new JMenuItem(str);
            mi.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
            mi.addActionListener(new ActionListener()
                {
                    public void actionPerformed(ActionEvent e)  
                    {
                        String a = e.getActionCommand();
                        a = msg.getText() + " $"  + a;//No i18n
                        msg.setText(a);
                    }
                }
            );
            jp.add(mi);
        }
        
        jp.show(jButton3, 0, 5 );      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
       if(NmsFilterFrame.standAlone)
       {
          chooser.setApproveButtonText("Attach");//No i18n
	  int retVal = chooser.showOpenDialog(new JFrame()); 
       }
       else
       {
            attachDialog.init();
            attachDialog.setDirectory("");
            attachDialog.setVisible(true);
            jf.getContentPane().setLayout(new BorderLayout());
            jf.getContentPane().add(attachDialog);
            jf.setSize (300, 200);
            jf.setTitle(NmsClientUtil.GetString(" File Attachment "));//No i18n
            jf.pack();
            jf.setVisible(true);
        }      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    
    }//GEN-LAST:event_jButton4ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        JPopupMenu jp = new JPopupMenu();

        Vector vec = new Vector();
        vec.addElement("category");//No i18n
        vec.addElement("entity");//No i18n
        vec.addElement("message");//No i18n
        vec.addElement("severity");//No i18n
        vec.addElement("source");//No i18n
        vec.addElement("groupName");//No i18n
        
        for(Enumeration en = vec.elements(); en.hasMoreElements();)
        {
            String str = (String)en.nextElement();
            JMenuItem mi = new JMenuItem(str);
            mi.setFont(NmsClientUtil.getFont("DIALOG"));//No i18n
            mi.addActionListener(new ActionListener()
                {
                    public void actionPerformed(ActionEvent e)  
                    {
                        String a = e.getActionCommand();
                        a = subject.getText() + " $"  + a;//No i18n
                        subject.setText(a);
                    }
                }
            );
            jp.add(mi);
        }
        
        jp.show(jButton2, 0,5 );      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {
	JPopupMenu jp = new JPopupMenu();
       
       JMenuItem mi = new JMenuItem("Help");//No i18n
       JPanel panel = new JPanel();

       String msgTxt = "<html>Sends E-mail when matching Events/Alerts are received. <br>Configure the mail server name, <br>port and authentication information correctly. <br>Event/alert Properties can be passed in the <br>mail subject and body fields. <br>Support for mail attachment is also available.<br> Refer Admin Guide for details.</html>";//No i18n
       
       /*JTextArea ep = new JTextArea();
       ep.setColumns(20);
       ep.setLineWrap(true);
       ep.setRows(10);
       ep.setBackground(new java.awt.Color(200, 200, 200));
       ep.setWrapStyleWord(true);*/
       JLabel ep = new JLabel();
       ep.setSize(300,200);
       ep.setText(msgTxt);
       panel.add(ep);

       mi.setLayout(new BorderLayout());
       mi.setPreferredSize(panel.getPreferredSize());
       mi.setFocusPainted(false);
       mi.add(panel, BorderLayout.CENTER);
       jp.setLayout(new BorderLayout());
       jp.add(mi, BorderLayout.CENTER);
       jp.show(helpButton,-60,-60);
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
     addAction.addNew=false;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {
        String nname = name.getText();
        Properties prop = getProperties();
        if(prop == null)
        {
            return;
        }
        
        boolean flag = addAction.addNewAction(prop, AddAction.sendEmailAction);//No i18n
        if(flag)
        {
            this.setVisible(false);
            this.dispose();
        }
        else
        {
            return;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) 
    {

        AuthDialog dialog = new AuthDialog(new JFrame(), true, cprop);
	NmsClientUtil.centerWindow(dialog);
        dialog.show();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        new SendEmailActionDialog(new javax.swing.JFrame(), true).show();
    }
    
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField file;
    private javax.swing.JTextField from;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextField name;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField server;
    private javax.swing.JPanel smallPanel;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
   
    public void setProperties(String selectedAction)
    {
     name.setEnabled(true); 
        if(selectedAction == null)
        {
            cprop = new Properties();
        }
        else
        {
            FilterAction action = (FilterAction)NotifierList.notifiers.get(selectedAction);
            if(action == null)
            {
                cprop = new Properties();
            }
            cprop = action.getProperties();
        }
        
        String nname = cprop.getProperty("name");
        if(nname == null)
	    {
		nname = "";
	    }
	else
	    {
		name.setEnabled(false);
	    }
        name.setText(nname);
        
        String nserver = cprop.getProperty("server");
        if(nserver == null) nserver = "";
        server.setText(nserver);
        
        String nfrom = cprop.getProperty("fromAddress");
        if(nfrom == null) nfrom = "";
        from.setText(nfrom);
        
        String nto = cprop.getProperty("toAddress");
        if(nto == null) nto = "";
        to.setText(nto);
        
        String nsubject  = cprop.getProperty("subject");
        if(nsubject == null) nsubject = "";
        subject.setText(nsubject);
        
        String nmessage = cprop.getProperty("message");
        if(nmessage == null) nmessage = "";
        msg.setText(nmessage);
        
        String fileName = cprop.getProperty("attachedfileName");
        if(fileName == null) fileName = "";
        file.setText(fileName);
    }
    
    public Properties getProperties()
    {
        String nname = name.getText();
        if(AddAction.checkNull(name, "Notification Name"))
        {
            return null;
        }
        cprop.setProperty("name", nname);
        
        String nserver = server.getText();
        if(AddAction.checkNull(server, "Server Name"))
        {
            return null;
        }
        cprop.setProperty("server", nserver);
        
        String nfrom = from.getText();
        if(AddAction.checkNull(from, "From Email ID"))
        {
            return null;
        }
        cprop.setProperty("fromAddress", nfrom);
        
        String nto = to.getText();
        if(AddAction.checkNull(to, "To Email ID"))
        {
            return null;
        }
        cprop.setProperty("toAddress", nto);
        
        String nsubject = subject.getText();
        if(AddAction.checkNull(subject, "subject"))
        {
            return null;
        }
        cprop.setProperty("subject", nsubject);
        
        String nmsg = msg.getText();
        cprop.setProperty("message", nmsg);
        
        String attFileName = file.getText();
        if(!attFileName.equals(""))
        {
            cprop.setProperty("attachedfileName", attFileName);
        }
        
        return cprop;
    }
    
    String fileUrl = "";
    public void actionPerformed(java.awt.event.ActionEvent e) {
        if((file.getText()).equals(""))
	{
	    fileUrl = null;
	}
	else
	{
	    fileUrl = file.getText();
	}

	if((e.getActionCommand()).equalsIgnoreCase("Open"))
	    {
		if(!NmsFilterFrame.standAlone)
		    {
			if(fileUrl == null || fileUrl.equalsIgnoreCase(""))
			    {
				String tempfileUrl = attachDialog.getSelectedFileUrl();
				fileUrl = tempfileUrl.substring(1);
			    }
			else
			    {
				String tempfileUrl = attachDialog.getSelectedFileUrl();
				String subfileUrl =  tempfileUrl.substring(1);
				fileUrl = fileUrl+','+subfileUrl; 
			    }
			jf.setVisible(false);
			file.setText(fileUrl);
		    }
	    }
	if((e.getActionCommand()).equalsIgnoreCase("Close"))
	    {
		jf.setVisible(false);
	    }
	if((e.getActionCommand()).equalsIgnoreCase("ApproveSelection"))
	    {
		String rtDir = com.adventnet.nms.util.PureUtils.rootDir;
		int len = rtDir.length();
		try {
		    File selectedFile = chooser.getSelectedFile();
		    if(fileUrl == null || fileUrl.equalsIgnoreCase(""))
			{
			    String tmpfileUrl = selectedFile.getCanonicalPath();
			    fileUrl = tmpfileUrl.substring(len);
			}
		    else
			{
			    
			    String tempfileUrl = selectedFile.getCanonicalPath();
			    tempfileUrl = tempfileUrl.substring(len);
			    fileUrl = fileUrl+','+tempfileUrl;
			}
		}
		catch(Exception ae) {
		    ae.printStackTrace();
		}
		
		file.setText(fileUrl);
	    }
    }   
}
